services:
  mongodb:
    image: mongo:latest
    container_name: market-lens-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: {MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: {MONGO_PASSWORD}
    volumes:
      - ./mongo_data:/data/db